"""multi-tenancy and academic years

Turns the single-school demo into a multi-tenant ERP foundation:

* `schools` — one row per customer (ERP_BLUEPRINT §0.2). A tenant is an
  independent school, not a branch.
* `academic_years` — a real session with a lifecycle, replacing the
  `String(9)` denormalised onto `class_sections` and `school_settings` (§3.1).
* `school_id` on every other table, enforced NOT NULL.
* `school_settings` is dropped; `schools` supersedes it.

Written by hand rather than left as autogenerated output because the generated
version added `school_id` as NOT NULL with no backfill, which fails on any
database that already has rows. Existing data is migrated onto a single school
derived from the old `school_settings` row.

Revision ID: 2170fa7c7d81
Revises: 6bfef3f61767
Create Date: 2026-09-06
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "2170fa7c7d81"
down_revision: str | None = "6bfef3f61767"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# Every table that gains a tenant key. `schools` is the tenant root and
# `academic_years` is created with its own column.
TENANT_TABLES = [
    "users",
    "students",
    "teachers",
    "parents",
    "parent_student",
    "class_sections",
    "subjects",
    "class_subject_teacher",
    "timetable_slots",
    "exams",
    "exam_schedule",
    "marks",
    "grade_bands",
    "fee_structures",
    "fee_invoices",
    "fee_payments",
    "attendance",
    "homework",
    "homework_submissions",
    "notices",
]

# Unique constraints that were global and must become per-tenant: two schools
# will both have an "admin" login and both may issue admission no SPS2024001.
RESCOPED_UNIQUES = [
    # (table, old constraint name, new name, columns)
    ("users", "users_login_id_key", "uq_user_login", ["school_id", "login_id"]),
    (
        "students",
        "students_admission_no_key",
        "uq_student_admission_no",
        ["school_id", "admission_no"],
    ),
    (
        "teachers",
        "teachers_employee_id_key",
        "uq_teacher_employee_id",
        ["school_id", "employee_id"],
    ),
    ("subjects", "subjects_code_key", "uq_subject_code", ["school_id", "code"]),
    (
        "fee_structures",
        "fee_structures_class_name_key",
        "uq_fee_structure_class",
        ["school_id", "class_name"],
    ),
    (
        "fee_payments",
        "fee_payments_receipt_no_key",
        "uq_payment_receipt_no",
        ["school_id", "receipt_no"],
    ),
]

_ENUM_SCHOOL_STATUS = sa.Enum(
    "onboarding", "active", "suspended", "closed", name="schoolstatus", native_enum=False
)
_ENUM_YEAR_STATUS = sa.Enum(
    "planning",
    "admissions_open",
    "active",
    "closing",
    "closed",
    "archived",
    name="academicyearstatus",
    native_enum=False,
)


def _timestamps() -> list[sa.Column]:
    return [
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            primary_key=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
    ]


def upgrade() -> None:
    bind = op.get_bind()

    # ---------------------------------------------------------------- schools
    op.create_table(
        "schools",
        sa.Column("code", sa.String(16), nullable=False, unique=True),
        sa.Column("name", sa.String(160), nullable=False),
        sa.Column("status", _ENUM_SCHOOL_STATUS, nullable=False, server_default="active"),
        sa.Column("address", sa.Text()),
        sa.Column("city", sa.String(80)),
        sa.Column("state", sa.String(80)),
        sa.Column("pincode", sa.String(10)),
        sa.Column("phone", sa.String(20)),
        sa.Column("email", sa.String(160)),
        sa.Column("website", sa.String(200)),
        sa.Column("logo_url", sa.Text()),
        sa.Column("primary_color", sa.String(9)),
        sa.Column("board", sa.String(20)),
        sa.Column("affiliation_no", sa.String(40)),
        *_timestamps(),
    )

    op.create_table(
        "academic_years",
        sa.Column("school_id", sa.BigInteger(), sa.ForeignKey("schools.id"), nullable=False),
        sa.Column("code", sa.String(9), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("status", _ENUM_YEAR_STATUS, nullable=False, server_default="planning"),
        sa.Column("is_current", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("promotion_completed_at", sa.Date()),
        sa.Column("result_published_at", sa.Date()),
        sa.Column("closed_at", sa.Date()),
        *_timestamps(),
        sa.UniqueConstraint("school_id", "code", name="uq_academic_year_code"),
    )
    op.create_index("ix_academic_years_school_id", "academic_years", ["school_id"])
    # At most one current year per school, enforced by the database (§3.1).
    op.create_index(
        "uq_academic_year_current",
        "academic_years",
        ["school_id"],
        unique=True,
        postgresql_where=sa.text("is_current"),
        sqlite_where=sa.text("is_current"),
    )

    # ------------------------------------------------- carry the old school over
    old = bind.execute(
        sa.text(
            "SELECT name, address, city, phone, email, logo_url, primary_color,"
            " academic_year FROM school_settings ORDER BY id LIMIT 1"
        )
    ).first()

    name = old.name if old else "Sunrise Public School"
    year_code = old.academic_year if old else "2025-26"

    bind.execute(
        sa.text(
            "INSERT INTO schools (code, name, status, address, city, state, phone,"
            " email, logo_url, primary_color, board, created_at, updated_at)"
            " VALUES (:code, :name, 'active', :address, :city, :state, :phone,"
            " :email, :logo_url, :primary_color, 'CBSE', CURRENT_TIMESTAMP,"
            " CURRENT_TIMESTAMP)"
        ),
        {
            "code": "SPS",
            "name": name,
            "address": old.address if old else None,
            "city": old.city if old else "Lucknow",
            "state": "Uttar Pradesh",
            "phone": old.phone if old else None,
            "email": old.email if old else None,
            "logo_url": old.logo_url if old else None,
            "primary_color": old.primary_color if old else "#5B4BE0",
        },
    )
    school_id = bind.execute(
        sa.text("SELECT id FROM schools WHERE code = 'SPS'")
    ).scalar_one()

    # One academic year per distinct string previously stored on class_sections,
    # plus the settings row's year so the current session always exists.
    codes = {
        r[0]
        for r in bind.execute(sa.text("SELECT DISTINCT academic_year FROM class_sections"))
        if r[0]
    }
    codes.add(year_code)
    for code in sorted(codes):
        start = int(code.split("-")[0])
        bind.execute(
            sa.text(
                "INSERT INTO academic_years (school_id, code, start_date, end_date,"
                " status, is_current, created_at, updated_at)"
                " VALUES (:sid, :code, :start, :end, :status, :cur,"
                " CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)"
            ),
            {
                "sid": school_id,
                "code": code,
                "start": f"{start}-04-01",
                "end": f"{start + 1}-03-31",
                "status": "active" if code == year_code else "closed",
                "cur": code == year_code,
            },
        )

    # ------------------------------------------------------- tenant key everywhere
    for table in TENANT_TABLES:
        op.add_column(table, sa.Column("school_id", sa.BigInteger(), nullable=True))
        bind.execute(sa.text(f"UPDATE {table} SET school_id = :sid"), {"sid": school_id})
        with op.batch_alter_table(table) as batch:
            batch.alter_column("school_id", existing_type=sa.BigInteger(), nullable=False)
            batch.create_foreign_key(
                f"fk_{table}_school", "schools", ["school_id"], ["id"]
            )
        op.create_index(f"ix_{table}_school_id", table, ["school_id"])

    # updated_at was nullable with onupdate only, so it stayed NULL until a row
    # was first modified — "never touched" and "touched at an unknown time" were
    # indistinguishable.
    for table in [*TENANT_TABLES, "schools", "academic_years"]:
        bind.execute(
            sa.text(f"UPDATE {table} SET updated_at = created_at WHERE updated_at IS NULL")
        )
        with op.batch_alter_table(table) as batch:
            batch.alter_column(
                "updated_at",
                existing_type=sa.DateTime(timezone=True),
                nullable=False,
                # server_default, not existing_server_default: SQLite's batch
                # mode rebuilds the table, and passing only `existing_` drops
                # the default, leaving a NOT NULL column nothing can insert
                # into. Caught by seeding a migrated database, which the test
                # suite does not do — it builds the schema from the models.
                server_default=sa.func.now(),
            )

    # ------------------------------------------- class_sections -> academic_year_id
    op.add_column(
        "class_sections", sa.Column("academic_year_id", sa.BigInteger(), nullable=True)
    )
    bind.execute(
        sa.text(
            "UPDATE class_sections SET academic_year_id = ("
            " SELECT id FROM academic_years"
            " WHERE academic_years.code = class_sections.academic_year"
            " AND academic_years.school_id = :sid)"
        ),
        {"sid": school_id},
    )
    with op.batch_alter_table("class_sections") as batch:
        batch.alter_column(
            "academic_year_id", existing_type=sa.BigInteger(), nullable=False
        )
        batch.create_foreign_key(
            "fk_class_sections_year", "academic_years", ["academic_year_id"], ["id"]
        )
        batch.drop_constraint("uq_class_section", type_="unique")
        batch.create_unique_constraint(
            "uq_class_section", ["academic_year_id", "class_name", "section"]
        )
        batch.drop_column("academic_year")
    op.create_index(
        "ix_class_sections_academic_year_id", "class_sections", ["academic_year_id"]
    )
    op.add_column("class_sections", sa.Column("capacity", sa.Integer()))
    op.add_column("class_sections", sa.Column("stream", sa.String(20)))
    op.add_column("class_sections", sa.Column("room", sa.String(20)))

    # -------------------------------------------------- per-tenant uniqueness
    # Postgres names a column-level UNIQUE `<table>_<column>_key` and lets it be
    # dropped by name. SQLite implements one as an unnamed auto-index that
    # cannot be dropped at all — the table would have to be rebuilt. Production
    # is Postgres, and SQLite is only ever used by the test suite, which builds
    # its schema from the models with `create_all` and never runs migrations.
    # So this step is a no-op on SQLite rather than a lie that appears to work.
    if bind.dialect.name != "sqlite":
        for table, old_name, new_name, cols in RESCOPED_UNIQUES:
            op.drop_constraint(old_name, table, type_="unique")
            op.create_unique_constraint(new_name, table, cols)

    op.create_index(
        "ix_users_school_role_login", "users", ["school_id", "role", "login_id"]
    )
    op.drop_index("ix_users_role_login_id", table_name="users")

    op.drop_table("school_settings")


def downgrade() -> None:
    raise NotImplementedError(
        "Irreversible: dropping schools would leave rows with no tenant and "
        "school_settings cannot be reconstructed for more than one school. "
        "Restore from backup instead."
    )
